services:
  # Base de datos vectorial
  chromadb:
    image: chromadb/chroma:0.4.24
    ports:
      - "8033:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  # API Backend (FastAPI + LangChain + RAG)
  backend:
    image: davidsmh233/soporte-inteligente-rag-backend
    build:
      context: ./backend
    ports:
      - "8502:8000"
    volumes:
      - ./obsidian_vault:/app/obsidian_vault:ro
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      - chromadb

  # Interfaz web (Streamlit)
  frontend:
    image: davidsmh233/soporte-inteligente-rag-frontend
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  chroma-data:
